### ISSUE TITLE
Cancel multiple search request

### ISSUE THREAD

**Issue by ChristophLabacher** [rundsk/dsk#102]
While the user is typing in the search, a search request is fired for every new letter (there is currently no debouncing). When a new search request is sent, the previous once should be canceled, so we don’t have to many running request. `Client.js` should probably take care of this.

**Comment by mariuswilms** [comment]
We can implement this on top of our current approach (I did this before its not too tricky), which uses old-school XMLHTTPRequest so we do not need to do extra work to pass Basic Authentication from the initial response to API requests.

Alternatively we can use axios, which allows for easy cancellation. Do you have experience with axios behind Basic Authentication?

**Comment by mariuswilms** [comment]
We don't have experience with axios and Basic Authentication. Also we probably want to keep the SDK dependency free. So we're going with a handknit implementation.

**Comment by christophlocher** [comment]
@mariuswilms I had a go at it – please take a look

**Comment by mariuswilms** [comment]
Implemented in https://github.com/rundsk/js-sdk/commit/45132b74
