### ISSUE TITLE
Add inline color documentation component

### ISSUE THREAD

**Issue by ChristophLabacher** [rundsk/dsk#109]
<img width="199" alt="image" src="https://user-images.githubusercontent.com/7572627/63602104-fff5b500-c5c6-11e9-9334-92f8a32376c4.png">

```
<Color color="#FF3300">Orangy Red</Color>
```

This component should be called `Color`, so we have to rename the current `Color` to `ColorCard`

**Comment by ChristophLabacher** [comment]
depends on #95

**Comment by mariuswilms** [comment]
#95 has been solved

**Comment by ChristophLabacher** [comment]
this one has too! 😊 https://rundsk.com/tree/The-Design-Definitions-Tree/Documents/Components/Inline-Color
