### ISSUE TITLE
Code highlighting

### ISSUE THREAD

**Issue by francawinter** [rundsk/dsk#118]
Please enhance the code components.
It would be very comfortable to be able to declare the programming language after the back ticks \`\`\`. In the frontend, the code should be colorful afterwards.

```
\```html
<div>Hello, I'm an example!</div>
\```
```

**Comment by mariuswilms** [comment]
We probably want to support both (1) providing language when using Markdown fenced code syntax and (2) when using the documentation code component directly.

As far as I know, @ChristophLabacher you're implementing (2).
Regarding (1), this should be possible too but we might need to change how the backend parses Markdown: https://github.com/russross/blackfriday/issues/195#issuecomment-138807484
