### ISSUE TITLE
Website rundsk.com responds with 502 Bad Gateway

### ISSUE THREAD

**Issue by stairjoke** [rundsk/dsk#142]
Has this project been abandoned, otherwise, it'd be nice to see the website revived.

**Comment by mariuswilms** [comment]
The website is back online, sorry for the interruption. Our instance run out of memory. No fortunately not abandoned, quite the opposite. We're currently preparing the next release which will include support for embedding components from your component library into DSK's interactive playgrounds. We're tracking the implementation through #75. Please stay tuned and thanks for using DSK!
